# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: CmdLine@2
  displayName: Install ninja
  inputs:
    script: 'sudo apt-get install ninja'
- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get install build-essential
      sudo apt-get install g++-arm-linux-gnueabihf
      sudo apt-get install gdb-multiarch
- task: CmdLine@2
  inputs:
    script: './bootstrap-vcpkg.sh -useSystemBinaries'
- task: CmdLine@2
  inputs:
    script: './vcpkg search wiringpi'
- task: CmdLine@2
  inputs:
    script: './vcpkg install wiringpi:arm-rasp'